### ISSUE TITLE
Optimized display for multiple scale extent changes  (last one only relevant)

### ISSUE THREAD

**Issue by mikedorais** [Esri/runtime-questions#118]
How well is the display pipeline optimized if your app submits multiple requests to change extent or scale so that it doesn't wast time drawing what is obsolete and only spend time on the latest extent and scale?
Local mobile map package?
Local Server?
Remote server/maps?

**Comment by mikedorais** [comment]
Answer as I heard it in session:
Internally there is a timer.  determined by APIS what is best.  Only deal with last one coming in with timer.
There is some internal code that cancels a request or never handles the results.
Please revise and confirm.
Thank you.

**Comment by ralfgottschalk** [comment]
Normally every time the map extent changes a new request for data is sent out, whether this request is from a local or remote server, or a local data source. However, as stated in the question, this would be extremely inefficient if you are actively interacting with the map, there could be hundreds of requests by simply panning or zooming in.  

To deal with this problem the Map View's behavior is governed by interaction and animation.  As the map is animating or interacting request we throttle the number of requests that can go out.  We throttle instead of prevent because as you pan and zoom you still want to get occasional updates so what you see stays current and provides a better user experience.

This behavior is slightly different depending on where data comes from and how the data is rendered.

For example, in a Graphics overlay in Dynamic Mode the graphics are represented on the GPU, so they will always draw.  In Static Mode, graphics are only drawn as needed, so when you zoom the redrawing will be throttled.  However, when panning, no redraw is required because we use what we already have and fill in what is missing, so it will always draw.  Local Tile layers will always draw, and nothing is throttled as drawing tiles on the screen is very cheap.  Data sources that consume online or local services do not throttle drawing but instead throttle the number of requests depending on the data source.  

The exact behavior varies slightly depending on the platform and the API you are using as each API (.NET, Java, Cocoa, Qt) render and interact with services in slightly different ways.  Internally in the core all these settings are tunable and we allow the Runtime API to optimize for their user experience.
