### ISSUE TITLE
v100 API Documentation for Xamarin

### ISSUE THREAD

**Issue by diogorosanelli** [Esri/runtime-questions#132]
There is any plan to update the Runtime API Documentation for Xamarin? The current version has a few details of API ....

**Comment by dotMorten** [comment]
The documentation has already been updated several times since release.
The API reference for Xamarin is near-identical to the WPF and UWP documentation, since it's created from the same common documentation, which also for the most part goes for the guide documentation.

The doc is the same place for all the .NET supported platforms, and all you need to do is pick the platform at the top:
![image](https://cloud.githubusercontent.com/assets/1378165/23808470/da525246-057e-11e7-8544-4bf7983e16e5.png)

Wrt samples, we often create cross-platform samples for the apps where that makes sense.
If you're missing a sample for a specific platform that's there for a different platform, the .NET API is quite similar across the supported platforms, that for the most part you can use the sample to learn from, and porting is rarely needed (apart from the UI pieces).

For anything that is very Xamarin specific, I would suggest using Xamarin's own documentation.

If there's areas you feel is lacking, I would love to hear your feedback.

**Comment by diogorosanelli** [comment]
Thanks @dotMorten for your reply, "Getting Started" section has a lot of details about Xamarin Platform, but "API Reference" section has a few details of objects and classes there I can use in my Applications.

**Comment by dotMorten** [comment]
@diogorosanelli We are constantly improving the API reference documentation, and pushing out updates over time. We know we're never done and always need more, and will exceed the amount of documentation we had for the previous generation of the API, which significantly grew over several years. The exact same effort is being put into the v100 releases now.

AFAIK the WPF API reference should be near-identical to the Xamarin counter-part (it's created from the same source). Are you finding that to not be the case? Are there specific areas you'd like to see enhanced first?

/CC @dkemlage
