### ISSUE TITLE
Preplanned Workflow

### ISSUE THREAD

**Issue by esride-ale** [Esri/runtime-questions#160]
1. Why are only extents/sqares supported in MapAreas?

2. Why the limitation of 16 MapAreas per WebMap?

Thanks,
Alex

**Comment by anttikajanus** [comment]
1. It's true that currently only envelopes are supported but we recognize the need for polygons. For example, if a field grew is doing a road maintenance, they would prefer to have data taken offline based on the road + buffer instead of the whole extent of the area. We did envelopes first so we got the functionality out and we have a chance to get user feedback about the functionality. Another reason behind this is that not all service types support polygons as parameters on the export operations.  A good example is a vector tile services that only allows us to export areas based on the envelopes. 

2. We wanted to have some limit for the areas and 16 was selected.  If you could add an unlimited number of areas to each webmap, it could introduce challenges to the backend and we wanted to direct users to manage areas based on the usage. With this, I mean that when you don't need areas, you should delete them because they will take a lot of space to host (larger the areas, more space it will take). The files (exported data from the services) are stored in a portal as items that are hidden from the user and are deleted when user deletes an area releasing the space. We are looking into the scenarios where you need more than that and would be very interested how you separate the areas and how many you would like to have.
