### ISSUE TITLE
Creating Runtime content again

### ISSUE THREAD

**Issue by faulconmjr** [Esri/runtime-questions#26]
The available Geoprocessing tool is too limiting and too high level.

Might there be finer grained objects to perform the tasks of creating runtime Geodatabases or vector tiles now or in the future?

**Comment by justincolville** [comment]
@faulconmjr it would be great to get more information on the workflows you need to suport

**Comment by coryeicher** [comment]
I second this request. Create Runtime Content also does not respect .mxd layer def queries, and therefore you cannot perform filtering as part of the runtime data creation process. Because the tool is course grained, we haven't found a way to do this that doesn't involve extracting to some kind of intermediate database. We prefer to avoid that since we already have a fairly complex system architecture. We have logged enhancement request w/ Esri support. The alternative appears to be to use the ArcGIS Server feature service 'CreateReplica' operation, this does support filtering. However, there don't seem to be AGS operations which support creating locators and network datasets in runtime format, so we end up with a 'mixed up' solution if we want to automation runtime data creation content, part python/GP and part AGS REST operations. Not ideal, at least for us...

**Comment by willcrick** [comment]
Create mobile map package in Pro is the preferred tool for provisioning data to Quartz version of the runtime.
