### ISSUE TITLE
A set of Questions on moving from Engine to Runtime

### ISSUE THREAD

**Issue by GeneRupelJr** [Esri/runtime-questions#36]
I attended the 2015 Esri Developer Summit.  During the summit, on multiple occasions, it was stated that one of the goals of the ArcGIS Runtime Quartz release is to: “Move Engine developers to Runtime”.  

With that in mind, I have the following questions.

First, I need to provide a description of the workflow were my Engine application runs.

I develop an ArcGIS Engine application with Microsoft Visual C++/MFC.

Different instances of the Engine app run on multiple computers on a standalone network.  This network is not connected to the internet.  There are incoming real-time data streams into the standalone network.  However, all other inputs to the system and all outputs pass through an air gap.  With the exception of the real-time data streams, the system is standalone.

A customer creates “work data” for the system.  The “work data” include shapefiles authored by ArcGIS Desktop.  These shapefiles are loaded into computer folders on the network and the folder paths are put into a database.  When my Engine app comes up, it gets the folder path names from the database, connects to those folders, and creates/displays layers in the MapControl.

After a set of “work” is done, “results” are loaded onto media and returned to the customer.  The “results” include shapefiles.

Both the “work data” coming in and the “results” going out are transferred via removable electronic media.

All software apps in this environment are desktop applications.  No Wi-Fi/cell phones are allowed anywhere near this network.

Now to specific questions.

Q01:  Will the ArcGIS Runtime Quartz release support the above workflow?

Q02:  As you can see, the above workflow is relatively primitive.  During the summit, the use of a “local server” with Runtime was mentioned for an offline workflow.
a)	Will a “local server” be useful in the above workflow?
b)	If so, can you provide a high level description of what a “local server” does and how it does it?  Can you provide a pointer to detailed documentation on the “local server”?

Q03:  Since the computers, this Engine app run on, are never connected to the internet then “unbound” licenses are needed.  Is a similar licensing scheme available for Runtime?

Q04:  Can a Runtime app and an Engine app run on the same computer (assuming the use of “unbound” licenses for all apps)? 

Q05: Can a Runtime app and ArcGIS Desktop run on the same computer (assuming the use of “unbound” licenses for all apps)?

Q06: Can Runtime apps created from different releases run on the same computer (assuming the use of “unbound” licenses for all apps)?

Q07:  In one seminar it was stated that “Esri would no longer be enhancing ArcObjects/ArcGIS Engine” and that “Runtime is the future for Engine developers”.
a)	Is there a date for when ArcGIS Engine will no longer be sold?
b)	Is there a date for when ArcGIS Engine will no longer have tech support?

Q08:  It was stated that “3D” is expected to be in the Runtime .NET 10.2.6 Release.
a)	Will this Runtime 3D be functionally equivalent to the Engine SceneControl.
b)	Does Runtime 3D need a server connection or can it work in an offline/standalone workflow?

Q09:  It was repeatedly stated/shown that Runtime is “high performance”.  Are there any published benchmarks comparing Runtime performance to Engine performance?

Q10:  In real-time, I need to move graphic markers across the map.  Does Runtime have equivalent functionality to the Engine GraphicTracker?

Q11:  Does the Runtime labeling allow for multiple labels for a marker/feature?

Thank for your time, 
Gene A Rupel, Jr 
Boeing Software Engineer                                                                                                          714-896-5514

**Comment by GeneRupelJr** [comment]
Anybody home?

**Comment by eric906** [comment]
Q01: Yes. These workflows will be supported at Quartz.

Q02: (a) The described workflow will not require local server. ArcGIS Runtime API will support the direct reading of shapefiles. Android and Java already so support this today, since 10.2.4.

Q03: By "unbound", do you mean no "license server" or concurrent license mechanism? If so, then yes. Standard Runtime licenses are baked into the app.

Q04: Yes. Engine and Runtime apps can co-exist. As for Runtime, multiple versions can co-exist as well.

Q05: Yes.

Q06: Yes.

Q07: Great questions (all of them). There is no end-of-life date determined for ArcObjects. It is the foundation for much of the existing ArcGIS Platform, including ArcGIS Desktop, Server Object Extensions (SOEs), Server Object Interceptors (SOI's), Geoprocessing engines, ArcPy, etc. Since it will take some time for some customers to migrate, and there are the few remaining gaps to be filled between ArcObjects and Runtime technologies (Quartz should finish that off), there is no hard date for EOL set at this time. However, we do STRONGLY encourage customers that are considering ArcObjects Java/Linux technology for any new dev projects to use the ArcGIS Runtime SDK for Java. Simply because almost all of the development team for Engine/AO Java is now full-throttle on Runtime development.

Q08: (b) .NET 10.2.6 3D will be CONNECTED only. 
         (a)...I'll need someone else to comment.

Q09: None at this time.

Q10: Yes. One of the first fundamental requirements and motivations for Runtime, since 1.0, was a "better", modern GraphicsTracker capability.

I really hope this helps! Thanks for these.
