### ISSUE TITLE
New / Missing functionality?

### ISSUE THREAD

**Issue by KrisFoster44** [Esri/runtime-questions#72]
In WPF and Silverlight we used to be able to do animation via storyboards.  Any chance for any animation functionality being added to the runtime in the future?

Timeframe on support for some missing functionality in the .geodatabase format?
1. Symbology types (i.e. Unique Values / Many Fields)
2. Symbology reference scaling (i.e. ArcMap Data Frame Property -> Reference Scale)
3. Annotation

**Comment by robertrader** [comment]
The ArcObjects Workspace has ExecuteSQL. The ArcGIS Pro SDK has the ArcGIS.Core.Data.DatabaseClient.ExecuteStatement

When will the runtime have a way to run SQL in the SQLLite datasources. This is need din the runtime, since the path is different for each os and the way to load the ST_GEOMETRY for sqlite requires path file location information. Since the SQLite connection is already initialized by runtime, with ST_GEOMETRY enabled, having an injection system makes for re-usable code.

**Comment by dotMorten** [comment]
@KrisFoster44 No plans to add animation to symbols. It is possible to use the overlays to render animated XAML content on top of the map in sync with your data, although it's not an alternative to render actual feature data with all the symbols animated. We demonstrated this in the Tips'n'Tricks session Wednesday, and recording will be available.
