### ISSUE TITLE
Roadmap of .NET SDK local server capabilities

### ISSUE THREAD

**Issue by shohei-51** [Esri/runtime-questions#81]
What is the plan for feature support of .NET SDK (WPF) local server capabilities (local dynamic service and local geoprocessing service)? Can user continue to use it or there will be alternative function to replace it?

**Comment by mbranscomb** [comment]
@shohei-51 
We have some really exciting changes planned for the LocalServer. As the mapping and data access capabilities of the core ArcGIS Runtime expand, the plan for the LocalServer within the ArcGIS Runtime SDK for .NET (also Java and Qt) is to focus on the local Geoprocessing capabilities. Focusing the LocalServer on geoprocessing enables us to expand the functionality to include additional tools in the areas of Analysis, Geocoding, Conversion, 3D Analyst, Spatial Analyst, Data Management, and include support for Lyr files, Mxd files, the creation of runtime content.

As part of this work, the LocalServer components will be split from the main SDK into a separately downloadable developer setup/install. The pattern for your app deployment will remain the same, where you need to include the LocalServer along with your application and the ArcGISRuntime deployment.

Where you currently use local map services and local feature services in 10.2.X, we anticipate in the Quartz services of releases you will be able to replicate the same functionality and provide an enhanced user experience via the use of mobile map packages, runtime geodatabases and feature layers, raster datasets and raster layers. 

We still expect to include support for LocalMapServices and LocalFeatureServices in our Quartz releases because they do provide access to some functionality/datatypes which may not initially be available in the first phase of releases. Plus you have built existing solutions around these local service types therefore it is likely to be important for you from the point of view of transition/migration to Quartz.

Thanks for your question

Cheers

Mike
