### ISSUE TITLE
Old map package performance in Quartz

### ISSUE THREAD

**Issue by mikedorais** [Esri/runtime-questions#97]
From WPF and .Net SDKs to Quartz you are moving from ArcMap generated map packages to the new mobile map package format.
I've been told that Quartz will still support the old map packages.
What group can they be added to (base map, reference, operational)?
I believe that within Quartz itself, the performance of mobile map packages will be better than the old map packages (came from a session here).
But considering a user continuing to use the old ArcMap generated map packages and just upgrading from a WPF or .Net SDK application, but continuing to use the same map packages, will they experience 1) same performance, 2) better performance or 3) worse performance?

**Comment by mbranscomb** [comment]
Map Packages (.mpks) are accessed via the LocalMapService class. LocalMapServices expose the MapServer REST endpoint. In Quartz, these would be added via the 'MapImageLayer' type instead of the previous ArcGISDynamicMapServiceLayer. These can be added to the OperationalLayers collection within the map.
Moving from 10.2.X to Quartz, the LocalServer has been upgraded to match Server 10.4. This does mean that MPKs (and GPKs) will need to be repackaged with ArcMap/ArcCatalog 10.4.
Performance will be the same, possibly better if any optimizations were made in ArcGIS Server 10.4.
